import '../globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { getPages } from '@/sanity/sanity-utils'
export const revalidate = 0


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My personal website',
  description: 'Generated by next + sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // get all of our pages
  const pages = await getPages()
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='flex justify-between items-center'>
          <Link href="/" className='bg-gradient-to-r drop-shadow
             from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent'>Home</Link>

             <div className='flex items-center gap-5 text-sm text-gray-600'>
              {pages.map((page) => (
                <Link key={page._id} href={`/${page.slug}`} className="hover:underline">{page.title}</Link>
              ))}
             </div>
        </header>
        <main className='py-20'>{children}</main>
        </body>
    </html>
  )
}
